# Generated by Django 2.0.1 on 2019-03-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'verbose_name': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(default='2019-03-18')),
                ('due_date', models.DateField(default='2019-03-18')),
                ('status', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='todolist.Status')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
