# Generated by Django 2.0.1 on 2019-03-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='description',
            new_name='content',
        ),
    ]
